rootProject.name = "DailyTracker"

include(":core:di")
include(":core:database")
include(":core:designsystem")
include(":features:objectives")
include(":features:dailylog")
include(":features:settings")
include(":features:timetracking")
include(":features:analytics")
include(":features:export")
include(":features:reviews")
include(":features:focuszones")
include(":features:timebudgets")
include(":features:habits")
include(":features:splash")
include(":features:achievements")
