package com.booking.worktracker.ui.localization

object EnglishStrings : Strings {
    // -- App / Window --
    override val appTitle = "Daily Work Tracker"
    override val dailyTracker = "Daily Tracker"

    // -- Navigation --
    override val navHome = "Home"
    override val navHistory = "History"
    override val navObjectives = "Objectives"
    override val navTimeTracking = "Time Tracking"
    override val navAnalytics = "Analytics"
    override val navExport = "Export"
    override val navSettings = "Settings"

    // -- Common actions --
    override val add = "Add"
    override val cancel = "Cancel"
    override val delete = "Delete"
    override val edit = "Edit"
    override val close = "Close"
    override val save = "Save"
    override val update = "Update"
    override val create = "Create"
    override val start = "Start"
    override val stop = "Stop"
    override val refresh = "Refresh"
    override val preview = "Preview"

    // -- Greetings --
    override val goodMorning = "Good Morning"
    override val goodAfternoon = "Good Afternoon"
    override val goodEvening = "Good Evening"
    override val readyToTrack = "Ready to track your day?"
    override fun dayStreak(count: Int) = "$count day streak"

    // -- Calendar --
    override val previousMonth = "Previous month"
    override val nextMonth = "Next month"
    override val dayMon = "Mon"
    override val dayTue = "Tue"
    override val dayWed = "Wed"
    override val dayThu = "Thu"
    override val dayFri = "Fri"
    override val daySat = "Sat"
    override val daySun = "Sun"

    // -- Daily Log Screen --
    override val startYourDay = "Start your day"
    override fun entriesCount(count: Int) = "$count entries"
    override fun viewingDate(date: String) = "Viewing: $date"
    override val dailyLog = "Daily Log"
    override val recordWorkEntries = "Record your work entries"
    override fun loggedCount(count: Int) = "$count logged"
    override val objectives = "Objectives"
    override val checkYourGoals = "Check your goals"
    override val quickTimer = "Quick Timer"
    override val startTrackingTime = "Start tracking time"
    override fun workEntriesCount(count: Int) = "Work Entries ($count)"
    override val addEntry = "Add Entry"
    override val noEntriesYet = "No entries yet. Click 'Add Entry' to log your work."
    override val entryDeleted = "\u2713 Entry deleted"
    override val entryAdded = "\u2713 Entry added successfully!"
    override val tags = "Tags"
    override val addNewTag = "Add new tag"
    override val noTagsYet = "No tags yet. Create your first tag!"
    override val deleteEntry = "Delete entry"

    // -- Add Entry Dialog --
    override val addWorkEntry = "Add Work Entry"
    override val whatDidYouAccomplish = "What did you accomplish?"
    override val entryPlaceholder = "Fixed bug in payment system"

    // -- New Tag Dialog --
    override val createNewTag = "Create New Tag"
    override val tagName = "Tag Name"
    override val tagNamePlaceholder = "e.g., bug-fix, meeting, feature"
    override val colorLabel = "Color:"

    // -- History / Log List --
    override val history = "History"
    override val noLogsYet = "No logs yet. Start logging your daily work!"
    override fun entryCount(count: Int) = if (count == 1) "1 entry" else "$count entries"
    override fun andMoreEntries(count: Int) = "  ... and $count more"
    override val logDetail = "Log Detail"
    override val workLog = "Work Log"

    // -- Objectives Screen --
    override val workObjectives = "Work Objectives"
    override val addObjective = "Add Objective"
    override val yearly = "Yearly"
    override val quarterly = "Quarterly"
    override val yearLabel = "Year:"
    override val quarterLabel = "Quarter:"
    override val previousYear = "Previous year"
    override val nextYear = "Next year"
    override val previousQuarter = "Previous quarter"
    override val nextQuarter = "Next quarter"
    override fun quarterYear(quarter: Int, year: Int) = "Q$quarter $year"
    override val noObjectivesYet = "No objectives yet. Add your first objective to start tracking progress!"
    override val inProgress = "In Progress"
    override val completed = "Completed"
    override val cancelled = "Cancelled"
    override val collapse = "Collapse"
    override val expand = "Expand"
    override val addChecklistItem = "Add checklist item"
    override val editObjective = "Edit Objective"
    override fun yearDisplay(year: Int) = "Year: $year"
    override fun quarterDisplay(quarter: Int, year: Int) = "Quarter: Q$quarter $year"
    override val objectiveTitle = "Objective Title"
    override val objectiveTitlePlaceholder = "e.g., Launch new product feature"
    override val descriptionOptional = "Description (Optional)"
    override val descriptionPlaceholder = "Add details about this objective..."

    // -- Checklist --
    override val addChecklistItemTitle = "Add Checklist Item"
    override val task = "Task"
    override val taskPlaceholder = "e.g., Complete design mockups"

    // -- Time Tracking Screen --
    override val timeTracking = "Time Tracking"
    override val startTimer = "Start Timer"
    override val stopTimer = "Stop Timer"
    override val addManual = "Add Manual"
    override val status = "Status"
    override val timerRunning = "Timer Running"
    override fun startedAt(time: String, category: String) = "Started at $time | $category"
    override val todaysSummary = "Today's Summary"
    override fun totalTime(formatted: String) = "Total: $formatted"
    override val timeEntries = "Time Entries"
    override val noTimeEntries = "No time entries for today. Start a timer or add a manual entry!"
    override fun timeRange(start: String, end: String?) = if (end != null) "$start - $end" else "$start - running"
    override val whatAreYouWorkingOn = "What are you working on?"
    override val workingOnPlaceholder = "e.g., Implementing feature X"
    override val category = "Category"
    override val addManualEntry = "Add Manual Entry"
    override val description = "Description"
    override val whatDidYouWorkOn = "What did you work on?"
    override val startTime = "Start Time"
    override val endTime = "End Time"
    override val timeFormatPlaceholder = "HH:MM"

    // -- Analytics Screen --
    override val analyticsAndInsights = "Analytics & Insights"
    override val noDataAvailable = "No data available yet. Start logging your work to see insights!"
    override val streaks = "Streaks"
    override val currentStreak = "Current Streak"
    override val bestStreak = "Best Streak"
    override val daysLogged = "Days Logged"
    override val overview = "Overview"
    override val totalEntries = "Total Entries"
    override val avgPerDay = "Avg/Day"
    override val mostActiveDay = "Most Active Day"
    override val total = "Total"
    override val checklistCompletion = "Checklist Completion"
    override fun percentValue(value: Int) = "$value%"
    override val tagUsage = "Tag Usage"
    override fun timesUsed(count: Int) = "$count times used"
    override val weeklyActivity = "Weekly Activity (Last 12 Weeks)"
    override fun activeDays(count: Int) = "$count/7 active days"
    override fun entriesCountLabel(count: Int) = "$count entries"
    override val recentDailyActivity = "Recent Daily Activity"
    override fun tagsCount(count: Int) = "$count tags"

    // -- Export Screen --
    override val exportData = "Export Data"
    override val dateRange = "Date Range"
    override val startDate = "Start Date"
    override val endDate = "End Date"
    override val dateFormatPlaceholder = "YYYY-MM-DD"
    override val include = "Include"
    override val workEntries = "Work Entries"
    override val format = "Format"
    override val plainText = "Plain Text"
    override val csv = "CSV"
    override val markdown = "Markdown"
    override val exporting = "Exporting..."
    override val exportToFile = "Export to File"
    override val exportDialogTitle = "Export Work Tracker Data"

    // -- Settings Screen --
    override val settings = "Settings"
    override val reminderTimes = "Reminder Times"
    override val morningReminder = "Morning Reminder"
    override val morningReminderDesc = "Daily reminder to review yesterday and plan your day"
    override val afternoonReminder = "Afternoon Reminder"
    override val afternoonReminderDesc = "Daily reminder to log your work (only if not logged yet)"
    override val timeHHMM = "Time (HH:MM)"
    override val saveSettings = "Save Settings"
    override val settingsSaved = "\u2713 Settings saved! Restart app to apply changes."
    override val dangerZone = "Danger Zone"
    override val dangerZoneDesc = "Permanently delete all logs, objectives, tags, time entries, and settings."
    override val deleteAllData = "Delete All Data"
    override val aboutReminders = "\u2139\uFE0F About Reminders"
    override val aboutRemindersMessage = "\u2022 Morning reminder helps you review yesterday's work and plan your day\n\u2022 Afternoon reminder only appears if you haven't logged work yet\n\u2022 Reminders appear as macOS notifications\n\u2022 You need to restart the app for time changes to take effect"
    override val deleteAllDataConfirmTitle = "Delete All Data?"
    override val deleteAllDataConfirmMessage = "This will permanently delete all your logs, objectives, tags, time entries, and settings. This cannot be undone."
    override val deleteEverything = "Delete Everything"
    override val allDataDeleted = "\u2713 All data deleted. Restart app for a fresh start."
    override val language = "Language"

    // -- Notifications --
    override val notificationMorningTitle = "Daily Work Tracker"
    override val notificationMorningMessage = "Good morning! Review yesterday and plan your day."
    override val notificationAfternoonTitle = "Daily Work Tracker"
    override val notificationAfternoonMessage = "Time to log your work for today!"

    // -- Error --
    override fun errorMessage(message: String) = "Error: $message"
}
